name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@master
      with:
        ruby-version: 3.0.0

    - name: Get TAG ref
      id: vars
      run: echo ::set-output name=tag::$(echo $(git rev-parse --short HEAD))

    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    # https://github.com/docker/build-push-action/issues/68
    # docker-build-push does not pull image
    - name: Pull cache from docker.pkg.github.com
      run: docker pull recario/urls || true

    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        build_args: BUILDKIT_INLINE_CACHE=1
        cache_froms: recario/urls:latest
        repository: recario/urls
        tags: latest,${{steps.vars.outputs.tag}}
        always_pull: true

    - name: Get new kubeconfig
      run: |
        mkdir -p $HOME/.kube
        curl --silent -X GET -H 'Authorization: Bearer ${{ secrets.DO_TOKEN }}' https://api.digitalocean.com/v2/kubernetes/clusters/${{ secrets.K8_ID }}/kubeconfig?expiry_seconds=3600 -o $HOME/.kube/config

    - name: Update web image for k8 cluster
      run: kubectl set image --record deployment/urls urls=recario/urls:${{steps.vars.outputs.tag}}

    - name: Verify deployment
      run: kubectl rollout status deployment/urls
